// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViennaMaps.Models
{
    public partial class AnalysisType
    {
        public AnalysisType()
        {
            Analysis = new HashSet<Analysis>();
        }

        public int AnalysisTypeId { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<Analysis> Analysis { get; set; }
    }
}