// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViennaMaps.Models
{
    public partial class AnalysisValue
    {
        public int AnalysisValueId { get; set; }
        public int AnalysisId { get; set; }
        public int AnalysisLocationId { get; set; }
        public string Value { get; set; }

        public virtual Analysis Analysis { get; set; }
    }
}