// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViennaMaps.Models
{
    public partial class Analysis
    {
        public Analysis()
        {
            AnalysisValue = new HashSet<AnalysisValue>();
            Project = new HashSet<Project>();
        }

        public int AnalyisId { get; set; }
        public string AnalysisName { get; set; }
        public int AnalysisTypeId { get; set; }
        public string MeasurmentUnit { get; set; }
        public string DiagramType { get; set; }

        public virtual AnalysisType AnalysisType { get; set; }
        public virtual ICollection<AnalysisValue> AnalysisValue { get; set; }

        public virtual ICollection<Project> Project { get; set; }
    }
}