// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViennaMaps.Models
{
    public partial class AnalysisValue
    {
        public AnalysisValue()
        {
            District = new HashSet<Location>();
        }

        public int AnalysisValueId { get; set; }
        public int AnalysisId { get; set; }
        public string Value { get; set; }
        public string Label { get; set; }

        public virtual Analysis Analysis { get; set; }

        public virtual ICollection<Location> District { get; set; }
    }
}