// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViennaMaps.Models
{
    public partial class District
    {
        public District()
        {
            AnalysisLocation = new HashSet<AnalysisLocation>();
        }

        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        public int DistrictNumber { get; set; }
        public int CityId { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }

        public virtual City City { get; set; }
        public virtual ICollection<AnalysisLocation> AnalysisLocation { get; set; }
    }
}