// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViennaMaps.Models
{
    public partial class Project
    {
        public Project()
        {
            Analysis = new HashSet<Analysis>();
            Layer = new HashSet<Layer>();
        }

        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public int ProjectScaleId { get; set; }

        public virtual ProjectScale ProjectScale { get; set; }

        public virtual ICollection<Analysis> Analysis { get; set; }
        public virtual ICollection<Layer> Layer { get; set; }
    }
}