// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViennaMaps.Models
{
    public partial class ProjectLocationAnalysisView
    {
        public int AnalyisId { get; set; }
        public string AnalysisName { get; set; }
        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        public int AnalysisValueId { get; set; }
        public int Expr1 { get; set; }
        public int Expr2 { get; set; }
        public string Value { get; set; }
        public string Label { get; set; }
        public int AnalysisTypeId { get; set; }
        public int Expr3 { get; set; }
        public int Expr4 { get; set; }
        public int AnalysisId { get; set; }
    }
}