// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViennaMaps.Models
{
    public partial class ProjectScale
    {
        public ProjectScale()
        {
            Project = new HashSet<Project>();
        }

        public int ProjectScaleId { get; set; }
        public string ScaleName { get; set; }

        public virtual ICollection<Project> Project { get; set; }
    }
}