// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViennaMaps.Models
{
    public partial class ProjectAnalysisView
    {
        public string AnalysisName { get; set; }
        public string MeasurmentUnit { get; set; }
        public string DiagramType { get; set; }
        public string ProjectName { get; set; }
        public string Value { get; set; }
        public string Label { get; set; }
        public int UilocationName { get; set; }
        public string DistrictName { get; set; }
    }
}