// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViennaMaps.Models
{
    public partial class Uilocation
    {
        public Uilocation()
        {
            Analysis = new HashSet<Analysis>();
        }

        public int UilocationId { get; set; }
        public int Uilocation1 { get; set; }

        public virtual ICollection<Analysis> Analysis { get; set; }
    }
}