// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViennaMaps.Models
{
    public partial class View1
    {
        public string LayerName { get; set; }
        public int LayerId { get; set; }
        public int ProjectId { get; set; }
        public int Expr1 { get; set; }
        public int Expr2 { get; set; }
        public string ProjectName { get; set; }
        public string ArcGisuri { get; set; }
        public string LayerLabel { get; set; }
        public string LayerDataSource { get; set; }
        public int LayerGroupId { get; set; }
        public int Expr3 { get; set; }
        public string GroupName { get; set; }
        public string GroupLabel { get; set; }
    }
}